import type {
  AgendaPriority,
  AgendaQueue,
  AgendaQueueFilter,
  AgendaService,
  AgendaStatus,
  AgendaTechnician,
  AgendaTechnicianAvailability,
} from "@/components/services/agenda/agenda-types"
import { addDays, formatDateKey, normalizeDate } from "@/components/services/agenda/agenda-utils"

export const agendaQueueFilters: Array<{
  id: AgendaQueueFilter
  label: string
  description: string
}> = [
  { id: "todos", label: "Tudo", description: "Mostra toda a operacao" },
  { id: "criticos", label: "Criticos", description: "Prioridade alta e prazos curtos" },
  { id: "instalacao", label: "Instalacao", description: "Novos ativos e upgrades" },
  { id: "manutencao", label: "Manutencao", description: "Preventiva e corretiva" },
  { id: "suporte", label: "Suporte", description: "Chamados recorrentes" },
  { id: "garantia", label: "Garantia", description: "Atendimentos cobertos" },
]

export const agendaStatusMeta: Record<
  AgendaStatus,
  {
    label: string
    chipClassName: string
  }
> = {
  confirmado: {
    label: "Confirmado",
    chipClassName: "border-primary/35 bg-primary/10 text-primary",
  },
  deslocamento: {
    label: "Deslocamento",
    chipClassName: "border-accent-foreground/25 bg-accent text-accent-foreground",
  },
  em_execucao: {
    label: "Em execucao",
    chipClassName: "border-primary/45 bg-primary/15 text-primary",
  },
  concluido: {
    label: "Concluido",
    chipClassName: "border-border/80 bg-secondary text-secondary-foreground",
  },
}

export const agendaPriorityMeta: Record<
  AgendaPriority,
  {
    label: string
    chipClassName: string
  }
> = {
  alta: {
    label: "Alta",
    chipClassName: "border-destructive/40 bg-destructive/10 text-destructive",
  },
  media: {
    label: "Media",
    chipClassName: "border-accent-foreground/25 bg-accent text-accent-foreground",
  },
  baixa: {
    label: "Baixa",
    chipClassName: "border-border/70 bg-muted/40 text-muted-foreground",
  },
}

export const agendaQueueMeta: Record<
  AgendaQueue,
  {
    label: string
    chipClassName: string
  }
> = {
  instalacao: {
    label: "Instalacao",
    chipClassName: "border-primary/35 bg-primary/10 text-primary",
  },
  manutencao: {
    label: "Manutencao",
    chipClassName: "border-accent-foreground/25 bg-accent text-accent-foreground",
  },
  suporte: {
    label: "Suporte",
    chipClassName: "border-border/80 bg-secondary text-secondary-foreground",
  },
  garantia: {
    label: "Garantia",
    chipClassName: "border-border/70 bg-muted/40 text-muted-foreground",
  },
}

export const availabilityMeta: Record<
  AgendaTechnicianAvailability,
  {
    label: string
    chipClassName: string
  }
> = {
  disponivel: {
    label: "Disponivel",
    chipClassName: "border-border/80 bg-secondary text-secondary-foreground",
  },
  em_rota: {
    label: "Em rota",
    chipClassName: "border-primary/35 bg-primary/10 text-primary",
  },
  folga: {
    label: "Folga",
    chipClassName: "border-border/70 bg-muted/40 text-muted-foreground",
  },
}

export const agendaModules = [
  {
    id: "painel",
    label: "Painel Operacional",
    description: "Resumo de capacidade e gargalos",
  },
  {
    id: "agenda",
    label: "Agenda Mensal",
    description: "Planejamento tatico da equipe",
  },
  {
    id: "rotas",
    label: "Roteirizacao",
    description: "Agrupamento por zona e deslocamento",
  },
  {
    id: "sla",
    label: "Monitor de SLA",
    description: "Prazos e prioridades em tempo real",
  },
]

const technicians: AgendaTechnician[] = [
  {
    id: "tec-01",
    name: "Bruna Siqueira",
    initials: "BS",
    specialty: "Infra e rede",
    base: "Zona Norte",
    availability: "em_rota",
    accent: "var(--primary)",
    accentForeground: "var(--primary-foreground)",
  },
  {
    id: "tec-02",
    name: "Caio Nogueira",
    initials: "CN",
    specialty: "Automacao industrial",
    base: "Zona Leste",
    availability: "disponivel",
    accent: "color-mix(in oklab, var(--chart-2) 78%, black 22%)",
    accentForeground: "var(--primary-foreground)",
  },
  {
    id: "tec-03",
    name: "Livia Mendes",
    initials: "LM",
    specialty: "CFTV e seguranca",
    base: "Centro",
    availability: "em_rota",
    accent: "var(--chart-5)",
    accentForeground: "var(--primary-foreground)",
  },
  {
    id: "tec-04",
    name: "Rafael Pires",
    initials: "RP",
    specialty: "Energia e nobreak",
    base: "Zona Sul",
    availability: "disponivel",
    accent: "color-mix(in oklab, var(--chart-4) 45%, black 55%)",
    accentForeground: "var(--primary-foreground)",
  },
  {
    id: "tec-05",
    name: "Thais Barreto",
    initials: "TB",
    specialty: "Servidores e backup",
    base: "ABC Paulista",
    availability: "folga",
    accent: "color-mix(in oklab, var(--chart-3) 58%, black 42%)",
    accentForeground: "var(--primary-foreground)",
  },
]

type ServiceBlueprint = Omit<AgendaService, "id" | "date"> & {
  dayOffset: number
}

const serviceBlueprints: ServiceBlueprint[] = [
  {
    dayOffset: -8,
    title: "Upgrade de firewall de borda",
    client: "Hospital Vida Plena",
    startTime: "08:15",
    endTime: "10:00",
    address: "Av. Marte, 482",
    district: "Centro",
    technicianId: "tec-01",
    status: "concluido",
    priority: "alta",
    queue: "instalacao",
    equipment: "Firewall Vision Secure X2",
    checklist: ["Backup da regra atual", "Teste de redundancia WAN"],
    slaMinutes: 180,
    estimateMinutes: 105,
  },
  {
    dayOffset: -7,
    title: "Preventiva de nobreak trifasico",
    client: "DataHub Logistica",
    startTime: "10:30",
    endTime: "12:00",
    address: "Rua Sideral, 77",
    district: "Mooca",
    technicianId: "tec-04",
    status: "concluido",
    priority: "media",
    queue: "manutencao",
    equipment: "Nobreak Atlas 20kVA",
    checklist: ["Mediar autonomia", "Registrar lote de baterias"],
    slaMinutes: 240,
    estimateMinutes: 90,
  },
  {
    dayOffset: -6,
    title: "Troca de switch core",
    client: "Coliseu Center Mall",
    startTime: "14:00",
    endTime: "16:30",
    address: "Av. Horizonte, 1401",
    district: "Barra Funda",
    technicianId: "tec-01",
    status: "concluido",
    priority: "alta",
    queue: "garantia",
    equipment: "Switch Vision Core 48p",
    checklist: ["Migrar VLAN", "Validar monitoramento SNMP"],
    slaMinutes: 150,
    estimateMinutes: 150,
  },
  {
    dayOffset: -5,
    title: "Ajuste de camera PTZ",
    client: "Condominio Solar do Vale",
    startTime: "09:00",
    endTime: "10:20",
    address: "Al. das Aguas, 219",
    district: "Vila Aurora",
    technicianId: "tec-03",
    status: "concluido",
    priority: "media",
    queue: "suporte",
    equipment: "Camera PTZ Vision Guard",
    checklist: ["Calibrar preset", "Verificar gravacao"],
    slaMinutes: 300,
    estimateMinutes: 80,
  },
  {
    dayOffset: -4,
    title: "Analise de falha intermitente em AP",
    client: "UniPrime Educacional",
    startTime: "11:00",
    endTime: "12:40",
    address: "Rua dos Professores, 18",
    district: "Saude",
    technicianId: "tec-02",
    status: "concluido",
    priority: "media",
    queue: "suporte",
    equipment: "Access Point Vision Air",
    checklist: ["Ler espectro", "Atualizar firmware"],
    slaMinutes: 240,
    estimateMinutes: 100,
  },
  {
    dayOffset: -3,
    title: "Instalacao de rack fechado",
    client: "Laboratorio Delta",
    startTime: "08:00",
    endTime: "10:30",
    address: "Rua Curva, 331",
    district: "Brooklin",
    technicianId: "tec-02",
    status: "concluido",
    priority: "baixa",
    queue: "instalacao",
    equipment: "Rack 44U Premium",
    checklist: ["Aterramento", "Organizacao de patch cords"],
    slaMinutes: 360,
    estimateMinutes: 150,
  },
  {
    dayOffset: -2,
    title: "Corretiva de gravador NVR",
    client: "Armazem Castelo",
    startTime: "13:10",
    endTime: "14:40",
    address: "Av. dos Inventarios, 52",
    district: "Ipiranga",
    technicianId: "tec-03",
    status: "concluido",
    priority: "alta",
    queue: "garantia",
    equipment: "NVR Vision Recorder 16",
    checklist: ["Reindexar discos", "Testar camaras remotas"],
    slaMinutes: 120,
    estimateMinutes: 90,
  },
  {
    dayOffset: -1,
    title: "Expansao de rede para filial",
    client: "Farmacia Horizonte",
    startTime: "09:30",
    endTime: "11:30",
    address: "Rua da Serra, 1090",
    district: "Vila Clementino",
    technicianId: "tec-01",
    status: "concluido",
    priority: "media",
    queue: "instalacao",
    equipment: "Switch Vision Edge 24",
    checklist: ["Criar segmentacao", "Homologar ponto de venda"],
    slaMinutes: 240,
    estimateMinutes: 120,
  },
  {
    dayOffset: 0,
    title: "Ativacao de link secundario",
    client: "Clinica Viver Bem",
    startTime: "07:50",
    endTime: "09:20",
    address: "Av. Atlante, 300",
    district: "Liberdade",
    technicianId: "tec-01",
    status: "deslocamento",
    priority: "alta",
    queue: "instalacao",
    equipment: "Roteador Vision Flex",
    checklist: ["Teste de failover", "Atualizar inventario"],
    slaMinutes: 90,
    estimateMinutes: 90,
  },
  {
    dayOffset: 0,
    title: "Preventiva trimestral de CFTV",
    client: "Centro Medico Safira",
    startTime: "09:40",
    endTime: "11:00",
    address: "Rua Granada, 62",
    district: "Tatuape",
    technicianId: "tec-03",
    status: "em_execucao",
    priority: "media",
    queue: "manutencao",
    equipment: "Painel CFTV Vision",
    checklist: ["Limpeza optica", "Teste de gravacao"],
    slaMinutes: 240,
    estimateMinutes: 80,
  },
  {
    dayOffset: 0,
    title: "Reconfiguracao de nobreak",
    client: "Studio Orion",
    startTime: "13:15",
    endTime: "14:45",
    address: "Alameda da Arte, 805",
    district: "Pinheiros",
    technicianId: "tec-04",
    status: "confirmado",
    priority: "alta",
    queue: "suporte",
    equipment: "Nobreak Atlas 10kVA",
    checklist: ["Ajuste de bypass", "Teste sob carga"],
    slaMinutes: 120,
    estimateMinutes: 90,
  },
  {
    dayOffset: 0,
    title: "Visita de aceite tecnico",
    client: "Industria Aster",
    startTime: "16:00",
    endTime: "17:10",
    address: "Rua Vapor, 143",
    district: "Santo Andre",
    technicianId: "tec-02",
    status: "confirmado",
    priority: "baixa",
    queue: "garantia",
    equipment: "Controladora Vision PLC",
    checklist: ["Emitir laudo", "Coletar assinatura digital"],
    slaMinutes: 300,
    estimateMinutes: 70,
  },
  {
    dayOffset: 1,
    title: "Substituicao de patch panel",
    client: "Conexao Express",
    startTime: "08:20",
    endTime: "10:00",
    address: "Rua do Porto, 111",
    district: "Lapa",
    technicianId: "tec-01",
    status: "confirmado",
    priority: "media",
    queue: "manutencao",
    equipment: "Patch Panel Cat6A",
    checklist: ["Mapear portas", "Atualizar diagrama"],
    slaMinutes: 240,
    estimateMinutes: 100,
  },
  {
    dayOffset: 1,
    title: "Diagnostico de latencia em ERP",
    client: "Mercado Boa Compra",
    startTime: "10:30",
    endTime: "11:50",
    address: "Av. Flores, 945",
    district: "Osasco",
    technicianId: "tec-02",
    status: "confirmado",
    priority: "alta",
    queue: "suporte",
    equipment: "Cluster SQL Vision",
    checklist: ["Coletar logs", "Analisar gargalo de rede"],
    slaMinutes: 120,
    estimateMinutes: 80,
  },
  {
    dayOffset: 2,
    title: "Expansao de storage para backup",
    client: "Clube Nautico Orion",
    startTime: "09:00",
    endTime: "11:40",
    address: "Av. das Velas, 205",
    district: "Santana",
    technicianId: "tec-05",
    status: "confirmado",
    priority: "media",
    queue: "instalacao",
    equipment: "Storage Vision Vault",
    checklist: ["Provisionar volume", "Executar backup teste"],
    slaMinutes: 360,
    estimateMinutes: 160,
  },
  {
    dayOffset: 2,
    title: "Inspecao de cabos de fibra",
    client: "Parque Tecnico Boreal",
    startTime: "14:00",
    endTime: "15:20",
    address: "Rua Prisma, 500",
    district: "Vila Mariana",
    technicianId: "tec-03",
    status: "confirmado",
    priority: "baixa",
    queue: "manutencao",
    equipment: "OTDR Vision Scan",
    checklist: ["Anotar perda por trecho", "Registro fotografico"],
    slaMinutes: 360,
    estimateMinutes: 80,
  },
  {
    dayOffset: 3,
    title: "Troca de controladora de acesso",
    client: "Condominio Aurora",
    startTime: "08:10",
    endTime: "10:30",
    address: "Rua das Acacias, 432",
    district: "Perdizes",
    technicianId: "tec-03",
    status: "confirmado",
    priority: "alta",
    queue: "garantia",
    equipment: "Controladora Vision Gate",
    checklist: ["Importar usuarios", "Teste de catraca"],
    slaMinutes: 90,
    estimateMinutes: 140,
  },
  {
    dayOffset: 3,
    title: "Homologacao de VPN site-to-site",
    client: "Grupo Mirante",
    startTime: "11:20",
    endTime: "12:30",
    address: "Av. Campo Limpo, 122",
    district: "Campo Limpo",
    technicianId: "tec-01",
    status: "confirmado",
    priority: "media",
    queue: "suporte",
    equipment: "Firewall Vision Secure X2",
    checklist: ["Verificar tunel", "Checklist de seguranca"],
    slaMinutes: 180,
    estimateMinutes: 70,
  },
  {
    dayOffset: 4,
    title: "Manutencao em central de alarme",
    client: "Transportes Arcus",
    startTime: "08:40",
    endTime: "09:50",
    address: "Rua dos Trilhos, 906",
    district: "Bras",
    technicianId: "tec-04",
    status: "confirmado",
    priority: "media",
    queue: "manutencao",
    equipment: "Central Vision Alarm",
    checklist: ["Teste de sensores", "Atualizar firmware"],
    slaMinutes: 240,
    estimateMinutes: 70,
  },
  {
    dayOffset: 4,
    title: "Instalacao de ponto de rede adicional",
    client: "Escola Viva Saber",
    startTime: "13:40",
    endTime: "15:20",
    address: "Rua Quatro Ventos, 290",
    district: "Jabaquara",
    technicianId: "tec-02",
    status: "confirmado",
    priority: "baixa",
    queue: "instalacao",
    equipment: "Kit Cabling Cat6",
    checklist: ["Certificar ponto", "Liberar mapa de patch"],
    slaMinutes: 420,
    estimateMinutes: 100,
  },
  {
    dayOffset: 5,
    title: "Recuperacao de matriz RAID",
    client: "Atacado Central Mix",
    startTime: "07:30",
    endTime: "10:10",
    address: "Av. das Nacoes, 77",
    district: "Guarulhos",
    technicianId: "tec-05",
    status: "confirmado",
    priority: "alta",
    queue: "suporte",
    equipment: "Servidor Vision Rack R2",
    checklist: ["Trocar disco danificado", "Rebuild monitorado"],
    slaMinutes: 120,
    estimateMinutes: 160,
  },
  {
    dayOffset: 6,
    title: "Troca de fonte redundante",
    client: "Clinica Equilibrio",
    startTime: "09:20",
    endTime: "10:40",
    address: "Al. Harmonia, 214",
    district: "Bela Vista",
    technicianId: "tec-04",
    status: "confirmado",
    priority: "media",
    queue: "garantia",
    equipment: "Servidor Vision Rack R1",
    checklist: ["Testar failover", "Atualizar inventario"],
    slaMinutes: 180,
    estimateMinutes: 80,
  },
  {
    dayOffset: 7,
    title: "Auditoria de checklist de backup",
    client: "Rede Bom Cuidado",
    startTime: "11:00",
    endTime: "12:15",
    address: "Rua das Laranjeiras, 65",
    district: "Santo Amaro",
    technicianId: "tec-05",
    status: "confirmado",
    priority: "baixa",
    queue: "manutencao",
    equipment: "Console Vision Backup",
    checklist: ["Conferencia de jobs", "Teste de restore rapido"],
    slaMinutes: 480,
    estimateMinutes: 75,
  },
  {
    dayOffset: 8,
    title: "Revisao de sensores perimetrais",
    client: "Haras Colina Verde",
    startTime: "08:30",
    endTime: "10:00",
    address: "Estrada Nova, km 12",
    district: "Itapecerica",
    technicianId: "tec-03",
    status: "confirmado",
    priority: "media",
    queue: "manutencao",
    equipment: "Kit Vision Secure Fence",
    checklist: ["Ajuste de sensibilidade", "Teste de disparo"],
    slaMinutes: 360,
    estimateMinutes: 90,
  },
  {
    dayOffset: 9,
    title: "Comissionamento de controladora",
    client: "Tech Yard Hub",
    startTime: "13:00",
    endTime: "15:40",
    address: "Av. Saturno, 58",
    district: "Sao Caetano",
    technicianId: "tec-02",
    status: "confirmado",
    priority: "alta",
    queue: "instalacao",
    equipment: "PLC Vision Control",
    checklist: ["Subir parametrizacao", "Teste com equipe local"],
    slaMinutes: 180,
    estimateMinutes: 160,
  },
  {
    dayOffset: 10,
    title: "Substituicao de camera externa",
    client: "Residencial Palmeiras",
    startTime: "09:10",
    endTime: "10:25",
    address: "Rua Bosque Alto, 911",
    district: "Vila Formosa",
    technicianId: "tec-03",
    status: "confirmado",
    priority: "media",
    queue: "garantia",
    equipment: "Camera Vision Dome",
    checklist: ["Ajustar angulo", "Sincronizar NVR"],
    slaMinutes: 240,
    estimateMinutes: 75,
  },
  {
    dayOffset: 11,
    title: "Replanejamento de enlaces",
    client: "Grupo Atlas",
    startTime: "15:20",
    endTime: "17:00",
    address: "Av. Industrial, 2150",
    district: "Maua",
    technicianId: "tec-01",
    status: "confirmado",
    priority: "alta",
    queue: "suporte",
    equipment: "Switch Vision Core",
    checklist: ["Atualizar rota", "Registrar novo baseline"],
    slaMinutes: 120,
    estimateMinutes: 100,
  },
  {
    dayOffset: 12,
    title: "Instalacao de AP em recepcao",
    client: "Centro Diagnostico Lume",
    startTime: "08:00",
    endTime: "09:30",
    address: "Rua Claridade, 74",
    district: "Aclimacao",
    technicianId: "tec-01",
    status: "confirmado",
    priority: "baixa",
    queue: "instalacao",
    equipment: "AP Vision Air Pro",
    checklist: ["Teste de cobertura", "Atualizar mapa Wi-Fi"],
    slaMinutes: 420,
    estimateMinutes: 90,
  },
  {
    dayOffset: 13,
    title: "Ajuste de relatorio de eventos",
    client: "Condominio Aurora",
    startTime: "10:40",
    endTime: "11:30",
    address: "Rua das Acacias, 432",
    district: "Perdizes",
    technicianId: "tec-03",
    status: "confirmado",
    priority: "media",
    queue: "suporte",
    equipment: "Console Vision Guard",
    checklist: ["Filtrar eventos", "Exportar historico"],
    slaMinutes: 240,
    estimateMinutes: 50,
  },
  {
    dayOffset: 14,
    title: "Preventiva de sala tecnica",
    client: "Universo Pharma",
    startTime: "13:30",
    endTime: "16:00",
    address: "Av. Fenix, 1200",
    district: "Tambore",
    technicianId: "tec-04",
    status: "confirmado",
    priority: "media",
    queue: "manutencao",
    equipment: "Painel de energia",
    checklist: ["Checklist termografico", "Aperto de bornes"],
    slaMinutes: 300,
    estimateMinutes: 150,
  },
  {
    dayOffset: 15,
    title: "Atualizacao de firmware em lote",
    client: "Rede SuperMax",
    startTime: "08:50",
    endTime: "10:50",
    address: "Rua das Palmeiras, 290",
    district: "Sao Bernardo",
    technicianId: "tec-02",
    status: "confirmado",
    priority: "baixa",
    queue: "garantia",
    equipment: "Switches Edge 24",
    checklist: ["Snapshot pre-mudanca", "Conferencia pos-update"],
    slaMinutes: 420,
    estimateMinutes: 120,
  },
  {
    dayOffset: 16,
    title: "Corretiva de sensor de porta",
    client: "Edificio Torre Norte",
    startTime: "11:45",
    endTime: "12:50",
    address: "Rua Inovacao, 920",
    district: "Vila Olimpia",
    technicianId: "tec-03",
    status: "confirmado",
    priority: "alta",
    queue: "suporte",
    equipment: "Sensor Vision Access",
    checklist: ["Substituir contato", "Teste de abertura"],
    slaMinutes: 120,
    estimateMinutes: 65,
  },
]

export function createAgendaMockData(referenceDate = new Date()) {
  const anchor = normalizeDate(referenceDate)

  const services: AgendaService[] = serviceBlueprints.map((item, index) => {
    const { dayOffset, ...service } = item

    return {
      ...service,
      id: `os-${String(index + 1).padStart(3, "0")}`,
      date: formatDateKey(addDays(anchor, dayOffset)),
    }
  })

  return {
    technicians,
    services,
  }
}
