import type { GenericField } from "@/components/layout/formComponent"

export const PRODUCT_BASE_FIELDS: GenericField[] = [
  {
    name: "name",
    label: "Nome do produto",
    type: "text",
    required: true,
    placeholder: "Ex: Notebook Vision Pro",
    colSpan: 2,
    section: "Identificacao",
    sectionDescription: "Dados principais para identificar o produto no catalogo.",
  },
  {
    name: "code",
    label: "Codigo SKU",
    type: "text",
    required: true,
    placeholder: "Gerado automaticamente",
    readOnly: true,
    disabled: true,
    autoFilled: true,
    description: "Gerado automaticamente no padrao PROD-XXXX.",
    section: "Identificacao",
  },
  {
    name: "category",
    label: "Categoria",
    type: "select",
    required: true,
    placeholder: "Selecione a categoria",
    options: [
      { label: "Hardware", value: "HARDWARE" },
      { label: "Software", value: "SOFTWARE" },
      { label: "Servicos", value: "SERVICES" },
      { label: "Perifericos", value: "PERIPHERALS" },
      { label: "Licencas", value: "LICENSES" },
      { label: "Infraestrutura", value: "INFRASTRUCTURE" },
      { label: "Outros", value: "OTHERS" },
    ],
    section: "Identificacao",
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    required: true,
    placeholder: "Selecione o status",
    options: [
      { label: "Ativo", value: "ACTIVE" },
      { label: "Inativo", value: "INACTIVE" },
      { label: "Sem estoque", value: "OUT_OF_STOCK" },
    ],
    defaultValue: "ACTIVE",
    section: "Identificacao",
  },
  {
    name: "supplier",
    label: "Fornecedor",
    type: "text",
    required: true,
    placeholder: "Ex: Distribuidora Alpha",
    section: "Comercial",
    sectionDescription: "Informacoes comerciais e de precificacao.",
  },
  {
    name: "brand",
    label: "Marca",
    type: "text",
    required: true,
    placeholder: "Ex: Dell",
    section: "Comercial",
  },
  {
    name: "price",
    label: "Preco de venda (R$)",
    type: "number",
    required: true,
    placeholder: "Ex: 1999.90",
    section: "Comercial",
  },
  {
    name: "cost",
    label: "Custo (R$)",
    type: "number",
    placeholder: "Ex: 1299.90",
    section: "Comercial",
  },
  {
    name: "stock",
    label: "Estoque atual",
    type: "number",
    required: true,
    placeholder: "Ex: 20",
    section: "Estoque e Operacao",
    sectionDescription: "Controle de estoque, localizacao e performance do item.",
  },
  {
    name: "minStock",
    label: "Estoque minimo",
    type: "number",
    required: true,
    placeholder: "Ex: 5",
    section: "Estoque e Operacao",
  },
  {
    name: "unitOfMeasure",
    label: "Unidade de medida",
    type: "select",
    required: true,
    placeholder: "Selecione a unidade",
    options: [
      { label: "Unidade (un)", value: "un" },
      { label: "Quilograma (kg)", value: "kg" },
      { label: "Grama (g)", value: "g" },
      { label: "Litro (L)", value: "L" },
      { label: "Mililitro (mL)", value: "mL" },
      { label: "Metro (m)", value: "m" },
      { label: "Centimetro (cm)", value: "cm" },
      { label: "Caixa (cx)", value: "cx" },
      { label: "Pacote (pct)", value: "pct" },
    ],
    defaultValue: "un",
    section: "Estoque e Operacao",
  },
  {
    name: "location",
    label: "Localizacao",
    type: "text",
    placeholder: "Ex: A1-02",
    section: "Estoque e Operacao",
  },
  {
    name: "percentage",
    label: "Margem (%)",
    type: "number",
    required: true,
    readOnly: true,
    autoFilled: true,
    description: "Calculada automaticamente com base no custo e preco de venda.",
    defaultValue: "0.00",
    section: "Estoque e Operacao",
  },
  {
    name: "monthlySales",
    label: "Vendas mensais",
    type: "number",
    readOnly: true,
    disabled: true,
    autoFilled: true,
    description: "Mantido automaticamente em 0 por enquanto.",
    defaultValue: "0",
    section: "Estoque e Operacao",
  },
  {
    name: "imageUrl",
    label: "Imagem do produto",
    type: "file",
    accept: "image/*",
    description: "Fixe uma imagem para facilitar a identificacao visual.",
    colSpan: 2,
    section: "Midia e Auditoria",
    sectionDescription: "Arquivos visuais e informacoes de criacao.",
  },
  {
    name: "createdBy",
    label: "Criado por",
    type: "text",
    required: true,
    placeholder: "Usuario logado",
    readOnly: true,
    disabled: true,
    autoFilled: true,
    description: "Preenchido automaticamente com o usuario autenticado.",
    section: "Midia e Auditoria",
  },
  {
    name: "description",
    label: "Descricao",
    type: "textarea",
    placeholder: "Resumo rapido para equipe comercial.",
    colSpan: 3,
    section: "Descricao",
    sectionDescription: "Observacoes relevantes para vendas e operacao.",
  },
]
