import type { Supplier } from "@/components/products/Supplier/supplier-models"

export const suppliersMock: Supplier[] = [
  {
    id: "sup-001",
    name: "Alpha Circuitos Industriais",
    tradeName: "Alpha Circuitos",
    segment: "eletronicos",
    status: "ativo",
    riskLevel: "baixo",
    leadTimeDays: 8,
    onTimeRate: 96.4,
    qualityScore: 98.1,
    annualSpend: 420_000,
    paymentTerm: "30 dias",
    minimumOrderValue: 4_500,
    activeContracts: 2,
    categories: ["Controladoras", "Sensores", "Fontes"],
    contactName: "Luciana Barros",
    contactEmail: "luciana.barros@alphacircuitos.com.br",
    contactPhone: "(19) 98765-1001",
    city: "Campinas",
    state: "SP",
    lastDeliveryAt: "2026-03-01",
    nextReviewAt: "2026-04-15",
  },
  {
    id: "sup-002",
    name: "Norte Cabos e Conectores",
    tradeName: "Norte Cabos",
    segment: "infraestrutura",
    status: "ativo",
    riskLevel: "medio",
    leadTimeDays: 15,
    onTimeRate: 88.7,
    qualityScore: 90.6,
    annualSpend: 310_000,
    paymentTerm: "45 dias",
    minimumOrderValue: 6_000,
    activeContracts: 1,
    categories: ["Cabos blindados", "Conectores", "Chicotes"],
    contactName: "Guilherme Lopes",
    contactEmail: "g.lopes@nortecabos.com",
    contactPhone: "(11) 97654-2002",
    city: "Sao Paulo",
    state: "SP",
    lastDeliveryAt: "2026-02-25",
    nextReviewAt: "2026-05-10",
  },
  {
    id: "sup-003",
    name: "Lumina Display Tech",
    tradeName: "Lumina",
    segment: "eletronicos",
    status: "avaliacao",
    riskLevel: "medio",
    leadTimeDays: 12,
    onTimeRate: 84.2,
    qualityScore: 87.4,
    annualSpend: 145_000,
    paymentTerm: "28 dias",
    minimumOrderValue: 3_500,
    activeContracts: 1,
    categories: ["Displays", "Touch panel"],
    contactName: "Raquel Matias",
    contactEmail: "raquel.matias@luminadisplay.com",
    contactPhone: "(31) 98888-3003",
    city: "Belo Horizonte",
    state: "MG",
    lastDeliveryAt: "2026-02-19",
    nextReviewAt: "2026-03-30",
  },
  {
    id: "sup-004",
    name: "Sigma Embalagens Tecnicas",
    tradeName: "Sigma Embalagens",
    segment: "embalagem",
    status: "ativo",
    riskLevel: "baixo",
    leadTimeDays: 5,
    onTimeRate: 97.8,
    qualityScore: 92.1,
    annualSpend: 98_000,
    paymentTerm: "21 dias",
    minimumOrderValue: 1_800,
    activeContracts: 1,
    categories: ["Caixas tecnicas", "Protecao anti-impacto"],
    contactName: "Marcelo Aquino",
    contactEmail: "marcelo.aquino@sigmaemb.com",
    contactPhone: "(41) 97777-4004",
    city: "Curitiba",
    state: "PR",
    lastDeliveryAt: "2026-03-04",
    nextReviewAt: "2026-05-02",
  },
  {
    id: "sup-005",
    name: "Prime Logistica Reversa",
    tradeName: "Prime Log",
    segment: "servicos",
    status: "ativo",
    riskLevel: "alto",
    leadTimeDays: 7,
    onTimeRate: 78.5,
    qualityScore: 82.9,
    annualSpend: 110_000,
    paymentTerm: "15 dias",
    minimumOrderValue: 2_000,
    activeContracts: 2,
    categories: ["Coleta", "Retorno de garantia", "Despacho"],
    contactName: "Fernanda Siqueira",
    contactEmail: "fernanda.siqueira@primelog.com.br",
    contactPhone: "(21) 96666-5005",
    city: "Rio de Janeiro",
    state: "RJ",
    lastDeliveryAt: "2026-02-28",
    nextReviewAt: "2026-03-26",
  },
  {
    id: "sup-006",
    name: "Hexa Quimica Aplicada",
    tradeName: "Hexa Quimica",
    segment: "insumos",
    status: "suspenso",
    riskLevel: "alto",
    leadTimeDays: 18,
    onTimeRate: 62.8,
    qualityScore: 75.4,
    annualSpend: 76_000,
    paymentTerm: "30 dias",
    minimumOrderValue: 5_500,
    activeContracts: 0,
    categories: ["Resinas", "Aditivos", "Tratamento de superficie"],
    contactName: "Carlos Monteiro",
    contactEmail: "carlos.monteiro@hexaquimica.com",
    contactPhone: "(51) 95555-6006",
    city: "Porto Alegre",
    state: "RS",
    lastDeliveryAt: "2026-01-30",
    nextReviewAt: "2026-03-18",
  },
  {
    id: "sup-007",
    name: "Orbit Batteries",
    tradeName: "Orbit",
    segment: "insumos",
    status: "ativo",
    riskLevel: "medio",
    leadTimeDays: 14,
    onTimeRate: 86.3,
    qualityScore: 89.2,
    annualSpend: 270_000,
    paymentTerm: "35 dias",
    minimumOrderValue: 7_000,
    activeContracts: 2,
    categories: ["Baterias", "Power packs"],
    contactName: "Isabela Nunes",
    contactEmail: "isabela.nunes@orbitbatteries.com",
    contactPhone: "(48) 94444-7007",
    city: "Florianopolis",
    state: "SC",
    lastDeliveryAt: "2026-03-02",
    nextReviewAt: "2026-04-08",
  },
  {
    id: "sup-008",
    name: "Vetor Metal Parts",
    tradeName: "Vetor Metal",
    segment: "infraestrutura",
    status: "ativo",
    riskLevel: "baixo",
    leadTimeDays: 9,
    onTimeRate: 94.1,
    qualityScore: 93.7,
    annualSpend: 190_000,
    paymentTerm: "40 dias",
    minimumOrderValue: 4_200,
    activeContracts: 1,
    categories: ["Suportes", "Fixadores", "Estruturas"],
    contactName: "Daniel Souza",
    contactEmail: "daniel.souza@vetormetal.com.br",
    contactPhone: "(27) 93333-8008",
    city: "Vitoria",
    state: "ES",
    lastDeliveryAt: "2026-02-24",
    nextReviewAt: "2026-04-22",
  },
]
