import type { Supplier } from "@/components/products/Supplier/supplier-models"

export const suppliersMock: Supplier[] = [
  {
    id: "sup-001",
    code: "FOR-001",
    name: "Alpha Circuitos Industriais",
    fantasyName: "Alpha Circuitos",
    segment: "eletronicos",
    risk: "baixo",
    contact: "Luciana Barros",
    city: "Campinas",
    state: "SP",
    status: "ativo",
    categories: "Controladoras, Sensores, Fontes",
    lead: "8 dias",
    location: "Centro de distribuicao Sudeste",
    phone: "(19) 98765-1001",
    email: "luciana.barros@alphacircuitos.com.br",
    minRequest: "R$ 4.500,00",
    lastDelivery: "2026-03-01",
  },
  {
    id: "sup-002",
    code: "FOR-002",
    name: "Norte Cabos e Conectores",
    fantasyName: "Norte Cabos",
    segment: "infraestrutura",
    risk: "medio",
    contact: "Guilherme Lopes",
    city: "Sao Paulo",
    state: "SP",
    status: "ativo",
    categories: "Cabos blindados, Conectores, Chicotes",
    lead: "15 dias",
    location: "Hub logistica Capital",
    phone: "(11) 97654-2002",
    email: "g.lopes@nortecabos.com",
    minRequest: "R$ 6.000,00",
    lastDelivery: "2026-02-25",
  },
  {
    id: "sup-003",
    code: "FOR-003",
    name: "Lumina Display Tech",
    fantasyName: "Lumina",
    segment: "eletronicos",
    risk: "medio",
    contact: "Raquel Matias",
    city: "Belo Horizonte",
    state: "MG",
    status: "avaliacao",
    categories: "Displays, Touch panel",
    lead: "12 dias",
    location: "Planta BH",
    phone: "(31) 98888-3003",
    email: "raquel.matias@luminadisplay.com",
    minRequest: "R$ 3.500,00",
    lastDelivery: "2026-02-19",
  },
  {
    id: "sup-004",
    code: "FOR-004",
    name: "Sigma Embalagens Tecnicas",
    fantasyName: "Sigma Embalagens",
    segment: "embalagem",
    risk: "baixo",
    contact: "Marcelo Aquino",
    city: "Curitiba",
    state: "PR",
    status: "ativo",
    categories: "Caixas tecnicas, Protecao anti-impacto",
    lead: "5 dias",
    location: "Base Sul",
    phone: "(41) 97777-4004",
    email: "marcelo.aquino@sigmaemb.com",
    minRequest: "R$ 1.800,00",
    lastDelivery: "2026-03-04",
  },
  {
    id: "sup-005",
    code: "FOR-005",
    name: "Prime Logistica Reversa",
    fantasyName: "Prime Log",
    segment: "servicos",
    risk: "alto",
    contact: "Fernanda Siqueira",
    city: "Rio de Janeiro",
    state: "RJ",
    status: "ativo",
    categories: "Coleta, Retorno de garantia, Despacho",
    lead: "7 dias",
    location: "Operacao Rio",
    phone: "(21) 96666-5005",
    email: "fernanda.siqueira@primelog.com.br",
    minRequest: "R$ 2.000,00",
    lastDelivery: "2026-02-28",
  },
  {
    id: "sup-006",
    code: "FOR-006",
    name: "Hexa Quimica Aplicada",
    fantasyName: "Hexa Quimica",
    segment: "insumos",
    risk: "alto",
    contact: "Carlos Monteiro",
    city: "Porto Alegre",
    state: "RS",
    status: "suspenso",
    categories: "Resinas, Aditivos, Tratamento de superficie",
    lead: "18 dias",
    location: "Unidade RS",
    phone: "(51) 95555-6006",
    email: "carlos.monteiro@hexaquimica.com",
    minRequest: "R$ 5.500,00",
    lastDelivery: "2026-01-30",
  },
]
