import type { ServiceCatalogItem } from "@/components/services/catalog/catalog-types"

export const serviceCatalogMockData: ServiceCatalogItem[] = [
  {
    id: "svc-001",
    code: "SVC-IMPL-001",
    name: "Implantacao ERP Core",
    description: "Kickoff, parametrizacao fiscal e treinamento inicial da operacao.",
    category: "Implantacao",
    billingModel: "project",
    status: "active",
    basePrice: 8900,
    slaHours: 8,
    avgExecutionHours: 36,
    activeContracts: 14,
    responsible: "Operacoes Enterprise",
    updatedAt: "2026-03-14",
  },
  {
    id: "svc-002",
    code: "SVC-SUP-247",
    name: "Suporte Tecnico 24x7",
    description: "Atendimento N1 e N2 com monitoramento continuo e priorizacao por SLA.",
    category: "Suporte",
    billingModel: "recurring",
    status: "active",
    basePrice: 1450,
    slaHours: 4,
    avgExecutionHours: 3,
    activeContracts: 62,
    responsible: "Service Desk",
    updatedAt: "2026-03-15",
  },
  {
    id: "svc-003",
    code: "SVC-SEC-011",
    name: "Auditoria de Seguranca",
    description: "Varredura de vulnerabilidades e plano de mitigacao em 3 etapas.",
    category: "Seguranca",
    billingModel: "project",
    status: "active",
    basePrice: 12800,
    slaHours: 24,
    avgExecutionHours: 22,
    activeContracts: 9,
    responsible: "CyberOps",
    updatedAt: "2026-03-08",
  },
  {
    id: "svc-004",
    code: "SVC-NOC-006",
    name: "Monitoramento NOC",
    description: "Supervisao proativa de infraestrutura com alertas em tempo real.",
    category: "Infraestrutura",
    billingModel: "recurring",
    status: "active",
    basePrice: 3100,
    slaHours: 2,
    avgExecutionHours: 1,
    activeContracts: 27,
    responsible: "NOC",
    updatedAt: "2026-03-12",
  },
  {
    id: "svc-005",
    code: "SVC-MIG-020",
    name: "Migracao para Nuvem",
    description: "Planejamento, movimentacao de carga e validacao de performance.",
    category: "Cloud",
    billingModel: "project",
    status: "draft",
    basePrice: 16300,
    slaHours: 16,
    avgExecutionHours: 44,
    activeContracts: 0,
    responsible: "Cloud Platform",
    updatedAt: "2026-03-03",
  },
  {
    id: "svc-006",
    code: "SVC-TRN-009",
    name: "Treinamento Operacional",
    description: "Capacitacao de usuarios-chave com trilha de aprendizado por area.",
    category: "Educacao",
    billingModel: "hourly",
    status: "active",
    basePrice: 320,
    slaHours: 48,
    avgExecutionHours: 2,
    activeContracts: 21,
    responsible: "Enablement",
    updatedAt: "2026-03-10",
  },
  {
    id: "svc-007",
    code: "SVC-DEV-031",
    name: "Customizacao Sob Demanda",
    description: "Evolucao de regras de negocio com homologacao assistida.",
    category: "Desenvolvimento",
    billingModel: "hourly",
    status: "active",
    basePrice: 280,
    slaHours: 12,
    avgExecutionHours: 5,
    activeContracts: 33,
    responsible: "Factory",
    updatedAt: "2026-03-13",
  },
  {
    id: "svc-008",
    code: "SVC-BKP-004",
    name: "Backup Gerenciado",
    description: "Politica de retencao, teste de restore e acompanhamento mensal.",
    category: "Infraestrutura",
    billingModel: "recurring",
    status: "inactive",
    basePrice: 980,
    slaHours: 6,
    avgExecutionHours: 2,
    activeContracts: 5,
    responsible: "Infra Core",
    updatedAt: "2026-02-28",
  },
  {
    id: "svc-009",
    code: "SVC-LPD-018",
    name: "Adequacao LGPD",
    description: "Mapeamento de dados, processos e plano de governanca continua.",
    category: "Compliance",
    billingModel: "project",
    status: "draft",
    basePrice: 9900,
    slaHours: 72,
    avgExecutionHours: 18,
    activeContracts: 2,
    responsible: "Governanca",
    updatedAt: "2026-03-01",
  },
  {
    id: "svc-010",
    code: "SVC-OPS-014",
    name: "Sustentacao Aplicacional",
    description: "Gestao de incidentes e pequenas melhorias para sistemas criticos.",
    category: "Suporte",
    billingModel: "recurring",
    status: "active",
    basePrice: 4200,
    slaHours: 8,
    avgExecutionHours: 4,
    activeContracts: 19,
    responsible: "Application Ops",
    updatedAt: "2026-03-16",
  },
]

export const serviceCatalogStatsMockData = [
  {
    label: "Servicos no Catalogo",
    value: "10",
    helper: "7 ativos para proposta imediata",
    tone: "text-sky-300",
    iconTone: "text-sky-200",
    icon: "wrench",
  },
  {
    label: "Contratos Ativos",
    value: "192",
    helper: "Volume total em operacao recorrente e projetos",
    tone: "text-emerald-300",
    iconTone: "text-emerald-200",
    icon: "activity",
  },
  {
    label: "Ticket Medio Base",
    value: "R$ 5.823,00",
    helper: "Referencia inicial para negociacao comercial",
    tone: "text-violet-300",
    iconTone: "text-violet-200",
    icon: "shield",
  },
  {
    label: "SLA Critico (<=8h)",
    value: "5",
    helper: "Servicos com maior exigencia operacional",
    tone: "text-amber-300",
    iconTone: "text-amber-200",
    icon: "check",
  },
] as const

export const serviceCatalogMockCategories = [
  "Implantacao",
  "Suporte",
  "Seguranca",
  "Infraestrutura",
  "Cloud",
  "Educacao",
  "Desenvolvimento",
  "Compliance",
] as const

export function getServiceCatalogMockById(serviceId?: string | null) {
  if (!serviceId) return serviceCatalogMockData[0] ?? null
  return serviceCatalogMockData.find((service) => service.id === serviceId) ?? null
}
